#!/usr/bin/env bash

# Bind these commands to some key combination; using them on the terminal kills their usefulness

# Dependencies:
# rofi - xclip

#BROWSER=firefox                            # Set your browser in your environment variables

BOOKMARKS_DIR="$XDG_DATA_HOME/bookmarks"    # Set the folder in which you want to store your bookmarks
Delim=">>"                                  # Set the delimiter between the bookmark's description and its URL

Program=${0##*/}

Usage(){
	while read ; do
		printf '%s\n' "$REPLY"
	done <<-EOF
		Usage:
		  $Program -o       - Open a saved bookmark
		  $Program -a       - Add a new bookmark
	EOF
}

ChooseFolder() {
	Destination="$BOOKMARKS_DIR/`ls $BOOKMARKS_DIR | rofi -dmenu -i -p 'Select or Add Folder' -l 20`"
}

[[ -z "$1" ]] && Usage && exit

while getopts ":ao" Options; do
	case $Options in
		a)  ChooseFolder && printf "%-40s\t${Delim} %s\n" "`rofi -dmenu -p 'Add Description' < /dev/null`" "`xclip -o`" >> $Destination
			echo "$(awk -F"${Delim}" '{print length($1), $0}' $Destination | sort -k1 -n | cut -d " " -f2-)" > $Destination
			exit
			;;

		o)  ChooseFolder
			if [ "$Destination" == "$BOOKMARKS_DIR/all" ]; then
				Url=`cat "$BOOKMARKS_DIR"/* | rofi -dmenu -i -p 'Select Bookmark' -l 20 | awk -F"${Delim}" '{print $2}'`
			elif [ "$Destination" != "$BOOKMARKS_DIR/" ]; then
				Url=`rofi -dmenu -i -p 'Select Bookmark' -l 20 < $Destination | awk -F"${Delim}" '{print $2}'`
			fi

			[[ -z "$Url" ]] || $BROWSER $Url > /dev/null &
			exit
			;;

		*)  Usage && exit
			;;
	esac
done
