#! /bin/bash

# Usage:
# search -g -> To search on Google
# search -d -> To search on DuckDuckGo

# Dependencies:
# rofi

# $BROWSER=firefox              #Set your browser in your enviromental variables

Program=${0##*/}

Usage(){
	while read ; do
		printf '%s\n' "$REPLY"
	done <<-EOF
		Usage:
		  $Program -g		- Search on Google
		  $Program -d		- Search on DuckDuckGo
	EOF
}

[[ -z "$1" ]] && Usage && exit

while getopts ":dg" Options
do
    case $Options in
        d)  Search=`rofi -dmenu -p 'DuckDuckGo' < /dev/null | tr ' ' '+'`
            [[ -z "$Search" ]] || $BROWSER "https://duckduckgo.com/?q=$Search" > /dev/null &
            exit
            ;;

        g)  Search=`rofi -dmenu -p 'Google' < /dev/null | tr ' ' '+'`
            [[ -z "$Search" ]] || $BROWSER "https://google.com/search?q=$Search" >/dev/null &
            exit
            ;;

        *) Usage && exit ;;
    esac
done
