#!/bin/sh

LapseDirectory="$HOME/Videos/lapse"
Ext="mkv"
printf -v Filename '%(%Y-%m-%d_%H-%M-%S)T'

notify-send  -t 2000 'REC' 'Timelapse' --icon=video-x-generic
ffmpeg -framerate 3 -f x11grab -s 2160,1440 -i :0.0+0,0 \
    -vf settb=\(1/10\),setpts=N/TB/10 -r 30 \
    -vcodec libx264 -crf 24 -qp 0 -preset ultrafast \
    -pix_fmt yuv444p -threads 0 \
    ${LapseDirectory}/${Filename}.${Ext}
