#!/bin/sh

LapseDirectory="$HOME/Videos/lapse"
Ext="mkv"
printf -v Filename '%(%Y-%m-%d_%H-%M-%S)T'

for File in `ls ${LapseDirectory}/*.${Ext}`; do
	printf "file '%s'\n" "$File" >> ${LapseDirectory}/list.txt
done

ffmpeg -f concat -i ${LapseDirectory}/list.txt \
	-c copy ${LapseDirectory}/${Filename}.${Ext}

rm ${LapseDirectory}/list.txt
