#!/bin/sh

VideoDirectory="$HOME/Videos"
Ext="mkv"
printf -v Filename '%(%Y-%m-%d_%H-%M-%S)T'

notify-send -t 2000 'REC' '2 Screens' --icon=video-x-generic
ffmpeg -f x11grab -video_size 2160x1440 -framerate 25 -i :0.0+0,1080 \
	-f x11grab -video_size 1920x1080 -framerate 25 -i :0.0 \
	-filter_complex '[1:0]scale=960x540[a],[0:0][a]overlay=(main_w-overlay_w):(main_h-overlay_h):format=yuv444' \
	-vcodec libx264 -preset ultrafast -crf 24 -qp 0 -pix_fmt yuv444p \
	${VideoDirectory}/${Filename}.${Ext}

