#!/bin/sh

VideoDirectory="$HOME/Videos"
Ext="mkv"
printf -v Filename '%(%Y-%m-%d_%H-%M-%S)T'

notify-send -t 2000 'REC' 'Screen' --icon=video-x-generic
ffmpeg -f x11grab -video_size 2160x1440 -framerate 25 -i :0.0 \
	-vcodec libx264 -preset ultrafast -crf 24 -qp 0 \
	-pix_fmt yuv444p ${VideoDirectory}/${Filename}.${Ext}
